### PR TITLE
New form and input components.

### PR DESCRIPTION
**Pull request by adriaanwm**
Includes:
- initialData that is put in state on component mount
- based on html input fields as much as possible
- custom validations
- default submit button shows ellipsis while submit in progress
- Default to only track input on change, but optionally update state onInput (each keypress) and onFocus/onBlur states for when needed
- fancy field and regular field examples
- non-custom validators
- textarea
- select
- debounce elements that track on input
- allow focus prop that focuses on render

### CODE REVIEW

**Comment by adriaanwm** [comment]
@staydecent the main differences from current Form are:
- onSubmit passed into Form component is given {data, onComplete, onError} and it isn't expected to return a promise. Could support both promises and callbacks if you want, but I prefer not using promises for onSubmit
- I stuck with Input component only (no TextField, Checkbox, etc) because I think the less we deviate from html the better. The Input components only job is to keep its value in sync with state
- The field labels only job is to add a label and hint/error to the Input that is its child

**Comment by staydecent** [comment]
Some inititial thoughts:

1. I was thinking we should go more in line with Promise standard, rather than an object with custom props. `onSubmit` should get a promise and can `.then` is success `.catch` is validation error. `onComplete` and `onError` sounds like a rewording of `resolve` and `reject`?

2. I think Input generalizes too much. A TextArea has different native HTML attrs than a text input. Same goes for checkbox and radio. Wrapping them in a single Parent component just seems like more if statements that may be harder to maintain than more explicit wrappers for each type. Ex:

```javascript
if (['radio', 'checkbox'].indexOf(type)) {
  // use onChange
} else {
  // use onInput
}
```

I'm not clear how in either case, there is deviation from HTML?

3. I believe that's all it does now?

**Comment by adriaanwm** [comment]
1. Yeah I don't like promises but you're right that it's just a rewording of resolve reject. I was annoyed that rejecting an object with field errors was causing the linter error, and I think using promises is more verbose.
```
onSubmit: ({data}) => new Promise((resolve, reject) => {
   ...
})

onSubmit: ({data, onSuccess, onError}) => {
   ...
}
```
Another reason I was annoyed by promises was that if you have code in onSubmit that raises, the Form component was catching the error and assuming it was formErrors then giving a very cryptic error. We could fix this problem in the Form component though by logging the error or having a specific form error exception type

**Comment by adriaanwm** [comment]
@staydecent One difference between checkbox in form2 and form is that form2 supports/enforces an array of values so
```
<Input type='checkbox' name='favourite-foods' value='tomatillo' />
<Input type='checkbox' name='favourite-foods' value='taco' />
```
would have state as some variation of `['tomatillo', 'taco']`
not sure how this would be accomplished in current form. Change the names on the checkboxes?

**Comment by adriaanwm** [comment]
@staydecent default validations is one of the biggest missing pieces here, doing it from the form when updating child props concerns me because of the nested fields issue. I think ideally the instructions for validations should stay in `index.js`. For now my preference is to have no auto validations and all validations have to be in the formProps just because it seems less likely to have unexpected behaviour

**Comment by staydecent** [comment]
My only concern is I've yet to actually implement custom validation. And never had to override the defaults I setup.

I basically always want to validate emails.
and telephone..

Most other validations I feel should come from the API.

Like for Winston. Say we actually wanted limitations on payment amounts, I wouldn't enforce that on the front-end, I'd wait for the response from API.

Especially since the errors are displayed to the user in the same manner (after trying to submit).

**Pull request merged**
